# ใช้ Node.js base image แบบ alpine
FROM node:18-bullseye

# ตั้งค่า working directory
RUN mkdir -p /usr/src/app/WebClient

WORKDIR /usr/src/app/WebClient

# คัดลอก package.json และ package-lock.json
COPY package*.json ./

RUN npm install --frozen-lockfile

# คัดลอกโค้ดทั้งหมดในโปรเจกต์
COPY . .

# เปิดพอร์ตสำหรับ Angular
EXPOSE 4200

# Start Angular in development mode
CMD ["npm", "start", "--", "--host", "0.0.0.0"]
 
