# ใช้ Node.js base image แบบ alpine
FROM node:alpine

# ตั้งค่า working directory
WORKDIR /usr/src/app

# คัดลอก package.json และ package-lock.json
COPY package*.json ./

# ติดตั้ง Angular CLI และ dependencies
RUN npm install -g @angular/cli && npm install

# คัดลอกโค้ดทั้งหมดในโปรเจกต์
COPY . .

# เปิดพอร์ตสำหรับ Angular
EXPOSE 4200

# รันคำสั่ง Angular serve
CMD ["ng", "serve", "--host", "0.0.0.0"]
 