# Stage 1: Build Angular App
FROM node:18 AS build-stage
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --frozen-lockfile
COPY . . 
RUN npm run build --configuration=production

# Stage 2: Serve with Nginx
FROM nginx:alpine
WORKDIR /usr/share/nginx/html  
COPY --from=build-stage /usr/src/app/dist/front-end /usr/share/nginx/html
EXPOSE 4200
CMD ["nginx", "-g", "daemon off;"]

