services:
  frontend:
    build:
      context: ./WebClient
      dockerfile: DOCKERFILE
    container_name: frontend-app
    ports:
      - "4200:4200"  # Exposing port 4200 for Angular via Nginx
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./WebService
      dockerfile: DOCKERFILE
    container_name: backend-app
    ports:
      - "3000:3000"  # Backend API exposed on port 3000
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: Team_Project
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Team_Project
      MYSQL_USER: Test
      MYSQL_PASSWORD: Password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always

volumes:
  mysql-data:
